refactor: treat 404 as an api error, handle 401 and 500 error
polarityio/confluence pull request #9
Opened 2023-02-06 23:36 UTC by ntsmith7

2023-04-16 20:15 UTC, sarus requested changes
@ntsmith7 Left some comments around the error handling updates.

Thank you!

2023-04-16 20:15 UTC, sarus commented on integration.js
>      if (response.statusCode === 400) {
Should 400 errors be handled as a miss here?  What does confluence return if no results are found.  I'm wondering if we should also handle this 400 error up in the new error handling logic and treat it as an error.  

It's possible that we were getting random 400 errors though and decided to just "swallow" those errors.  Have you seen this happen at all during your development?

2023-04-19 23:23 UTC, ntsmith7 commented on integration.js
>      if (response.statusCode === 400) {
Looking at the documentation,  I don't think the 400s should be handled as a miss - the API will return a 200 for missed results, with an empty array as the body value. I did not run into any random 400 errors while working on this.

The change I'm committing will return an error for 400s.

2023-04-20 19:19 UTC, sarus approved these changes
@ntsmith7 This looks good to me. Thank you for the work on it.  Since this is already in `develop` please move the ticket to QA and we'll have Neil QA off of this `develop` branch.  Once it passes QA then you can merge.

2023-04-20 19:38 UTC, merged